/* The following code was generated by JFlex 1.3.5 on 24/2/21 12:17 */

package lex.generado;
import lex.manual.SimbolosTerminales; 
import lex.manual.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 24/2/21 12:17 from the specification file
 * <tt>file:/C:/Users/claud/Documents/UNIVERSIDAD/05_Quinto/Segundo_cuatri/Procesadores de Lenguaje/Github - Lazaro/ProcesadoresLenguaje/Eclipse/Prueba/lexer.jflex</tt>
 */
public class Lexer implements SimbolosTerminales {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\16\0\4\0\1\24\3\0"+
    "\1\0\3\0\1\35\1\36\1\14\1\7\1\0\1\10\1\12\1\13"+
    "\1\4\1\33\1\31\1\32\6\11\1\0\1\34\1\0\1\37\2\0"+
    "\1\23\1\16\3\27\1\16\1\27\2\30\1\21\21\30\4\25\1\20"+
    "\1\25\27\22\1\5\2\22\1\25\1\6\2\25\41\25\2\25\4\25"+
    "\4\25\1\25\2\25\1\25\7\25\1\25\4\25\1\25\5\25\1\25"+
    "\1\26\7\25\1\26\3\25\1\26\4\25\1\0\1\15\3\0\1\0"+
    "\2\0\1\15\6\0\1\17\7\0\1\17\3\0\1\17\5\0\1\17"+
    "\3\0\1\0\2\0\1\17\u01c7\0\4\0\14\0\16\0\5\0\7\0"+
    "\1\0\1\0\1\0\21\0\160\0\5\0\1\0\2\0\2\0\4\0"+
    "\1\0\1\0\6\0\1\0\1\0\3\0\1\0\1\0\1\0\24\0"+
    "\1\0\123\0\1\0\213\0\1\0\5\0\2\0\246\0\1\0\46\0"+
    "\2\0\1\0\6\0\51\0\6\0\1\0\1\0\55\0\1\0\1\0"+
    "\1\0\2\0\1\0\2\0\1\0\1\0\10\0\33\0\4\0\4\0"+
    "\15\0\6\0\5\0\1\0\4\0\13\0\1\0\1\0\3\0\53\0"+
    "\37\0\4\0\2\0\1\0\143\0\1\0\1\0\10\0\1\0\6\0"+
    "\2\0\2\0\1\0\4\0\2\0\12\0\3\0\2\0\1\0\17\0"+
    "\1\0\1\0\1\0\36\0\33\0\2\0\131\0\13\0\1\0\16\0"+
    "\12\0\41\0\11\0\2\0\4\0\1\0\2\0\1\0\30\0\4\0"+
    "\1\0\11\0\1\0\3\0\1\0\5\0\22\0\31\0\3\0\4\0"+
    "\13\0\65\0\25\0\1\0\22\0\13\0\61\0\66\0\3\0\1\0"+
    "\22\0\1\0\7\0\12\0\2\0\2\0\12\0\1\0\20\0\3\0"+
    "\1\0\10\0\2\0\2\0\2\0\26\0\1\0\7\0\1\0\1\0"+
    "\3\0\4\0\2\0\1\0\1\0\7\0\2\0\2\0\2\0\3\0"+
    "\1\0\10\0\1\0\4\0\2\0\1\0\3\0\2\0\2\0\12\0"+
    "\4\0\7\0\2\0\1\0\1\0\2\0\3\0\1\0\6\0\4\0"+
    "\2\0\2\0\26\0\1\0\7\0\1\0\2\0\1\0\2\0\1\0"+
    "\2\0\2\0\1\0\1\0\5\0\4\0\2\0\2\0\3\0\3\0"+
    "\1\0\7\0\4\0\1\0\1\0\7\0\14\0\3\0\1\0\13\0"+
    "\3\0\1\0\11\0\1\0\3\0\1\0\26\0\1\0\7\0\1\0"+
    "\2\0\1\0\5\0\2\0\1\0\1\0\10\0\1\0\3\0\1\0"+
    "\3\0\2\0\1\0\17\0\2\0\2\0\2\0\12\0\1\0\1\0"+
    "\7\0\1\0\6\0\1\0\3\0\1\0\10\0\2\0\2\0\2\0"+
    "\26\0\1\0\7\0\1\0\2\0\1\0\5\0\2\0\1\0\1\0"+
    "\7\0\2\0\2\0\2\0\3\0\7\0\3\0\4\0\2\0\1\0"+
    "\3\0\2\0\2\0\12\0\1\0\1\0\20\0\1\0\1\0\1\0"+
    "\6\0\3\0\3\0\1\0\4\0\3\0\2\0\1\0\1\0\1\0"+
    "\2\0\3\0\2\0\3\0\3\0\3\0\14\0\4\0\5\0\3\0"+
    "\3\0\1\0\4\0\2\0\1\0\6\0\1\0\16\0\12\0\11\0"+
    "\1\0\6\0\5\0\10\0\1\0\3\0\1\0\27\0\1\0\20\0"+
    "\3\0\1\0\7\0\1\0\3\0\1\0\4\0\7\0\2\0\1\0"+
    "\3\0\5\0\2\0\2\0\2\0\12\0\20\0\1\0\3\0\1\0"+
    "\10\0\1\0\3\0\1\0\27\0\1\0\12\0\1\0\5\0\2\0"+
    "\1\0\1\0\7\0\1\0\3\0\1\0\4\0\7\0\2\0\7\0"+
    "\1\0\1\0\2\0\2\0\2\0\12\0\1\0\2\0\15\0\4\0"+
    "\11\0\1\0\3\0\1\0\51\0\2\0\1\0\7\0\1\0\3\0"+
    "\1\0\4\0\1\0\5\0\3\0\1\0\7\0\3\0\2\0\2\0"+
    "\12\0\12\0\6\0\1\0\3\0\1\0\22\0\3\0\30\0\1\0"+
    "\11\0\1\0\1\0\2\0\7\0\3\0\1\0\4\0\6\0\1\0"+
    "\1\0\1\0\10\0\6\0\12\0\2\0\2\0\15\0\60\0\1\0"+
    "\2\0\7\0\4\0\10\0\10\0\1\0\12\0\47\0\2\0\1\0"+
    "\1\0\1\0\5\0\1\0\30\0\1\0\1\0\1\0\12\0\1\0"+
    "\2\0\11\0\1\0\2\0\5\0\1\0\1\0\1\0\6\0\2\0"+
    "\12\0\2\0\4\0\40\0\1\0\27\0\2\0\6\0\12\0\13\0"+
    "\1\0\1\0\1\0\1\0\1\0\4\0\2\0\10\0\1\0\44\0"+
    "\4\0\24\0\1\0\2\0\5\0\13\0\1\0\44\0\11\0\1\0"+
    "\71\0\53\0\24\0\1\0\12\0\6\0\6\0\4\0\4\0\3\0"+
    "\1\0\3\0\2\0\7\0\3\0\4\0\15\0\14\0\1\0\17\0"+
    "\2\0\46\0\1\0\1\0\5\0\1\0\2\0\53\0\1\0\u014d\0"+
    "\1\0\4\0\2\0\7\0\1\0\1\0\1\0\4\0\2\0\51\0"+
    "\1\0\4\0\2\0\41\0\1\0\4\0\2\0\7\0\1\0\1\0"+
    "\1\0\4\0\2\0\17\0\1\0\71\0\1\0\4\0\2\0\103\0"+
    "\2\0\3\0\40\0\20\0\20\0\126\0\2\0\6\0\3\0\u026c\0"+
    "\2\0\21\0\1\0\32\0\5\0\113\0\3\0\13\0\7\0\15\0"+
    "\1\0\4\0\3\0\13\0\22\0\3\0\13\0\22\0\2\0\14\0"+
    "\15\0\1\0\3\0\1\0\2\0\14\0\64\0\40\0\3\0\1\0"+
    "\3\0\2\0\1\0\2\0\12\0\41\0\4\0\1\0\12\0\6\0"+
    "\131\0\7\0\5\0\2\0\42\0\1\0\1\0\5\0\106\0\12\0"+
    "\37\0\1\0\14\0\4\0\14\0\12\0\12\0\36\0\2\0\5\0"+
    "\13\0\54\0\4\0\32\0\6\0\12\0\46\0\27\0\5\0\4\0"+
    "\65\0\12\0\1\0\35\0\2\0\13\0\6\0\12\0\15\0\1\0"+
    "\10\0\16\0\1\0\2\0\77\0\5\0\57\0\21\0\7\0\4\0"+
    "\12\0\21\0\11\0\14\0\3\0\36\0\15\0\2\0\12\0\54\0"+
    "\16\0\14\0\44\0\24\0\10\0\12\0\3\0\3\0\12\0\44\0"+
    "\2\0\11\0\7\0\53\0\2\0\3\0\20\0\3\0\1\0\25\0"+
    "\4\0\1\0\6\0\1\0\2\0\3\0\1\0\5\0\300\0\72\0"+
    "\1\0\5\0\u0116\0\2\0\6\0\2\0\46\0\2\0\6\0\2\0"+
    "\10\0\1\0\1\0\1\0\1\0\1\0\1\0\1\0\37\0\2\0"+
    "\65\0\1\0\7\0\1\0\1\0\3\0\3\0\1\0\7\0\3\0"+
    "\4\0\2\0\6\0\4\0\15\0\5\0\3\0\1\0\7\0\16\0"+
    "\5\0\32\0\5\0\20\0\2\0\23\0\1\0\13\0\5\0\1\0"+
    "\12\0\1\0\1\0\15\0\1\0\20\0\15\0\3\0\40\0\20\0"+
    "\15\0\4\0\1\0\3\0\14\0\21\0\1\0\4\0\1\0\2\0"+
    "\12\0\1\0\1\0\3\0\5\0\6\0\1\0\1\0\1\0\1\0"+
    "\1\0\1\0\4\0\1\0\13\0\2\0\4\0\5\0\5\0\4\0"+
    "\1\0\21\0\51\0\u0a77\0\57\0\1\0\57\0\1\0\205\0\6\0"+
    "\4\0\3\0\2\0\14\0\46\0\1\0\1\0\5\0\1\0\2\0"+
    "\70\0\7\0\1\0\17\0\1\0\27\0\11\0\7\0\1\0\7\0"+
    "\1\0\7\0\1\0\7\0\1\0\7\0\1\0\7\0\1\0\7\0"+
    "\1\0\7\0\1\0\40\0\57\0\1\0\u01d5\0\3\0\31\0\11\0"+
    "\6\0\1\0\5\0\2\0\5\0\4\0\126\0\2\0\2\0\2\0"+
    "\3\0\1\0\132\0\1\0\4\0\5\0\53\0\1\0\136\0\21\0"+
    "\40\0\60\0\20\0\u0200\0\u19c0\0\100\0\u51fd\0\3\0\u048d\0\103\0"+
    "\56\0\2\0\u010d\0\3\0\20\0\12\0\2\0\24\0\57\0\1\0"+
    "\4\0\12\0\1\0\37\0\2\0\120\0\2\0\45\0\11\0\2\0"+
    "\147\0\2\0\65\0\2\0\11\0\52\0\15\0\1\0\3\0\1\0"+
    "\4\0\1\0\27\0\5\0\4\0\1\0\13\0\1\0\7\0\64\0"+
    "\14\0\2\0\62\0\22\0\12\0\12\0\6\0\22\0\6\0\3\0"+
    "\1\0\1\0\2\0\13\0\34\0\10\0\2\0\27\0\15\0\14\0"+
    "\35\0\3\0\4\0\57\0\16\0\16\0\1\0\12\0\6\0\5\0"+
    "\1\0\12\0\12\0\5\0\1\0\51\0\16\0\11\0\3\0\1\0"+
    "\10\0\2\0\2\0\12\0\6\0\27\0\3\0\1\0\3\0\62\0"+
    "\1\0\1\0\3\0\2\0\2\0\5\0\2\0\1\0\1\0\1\0"+
    "\30\0\3\0\2\0\13\0\5\0\2\0\3\0\2\0\12\0\6\0"+
    "\2\0\6\0\2\0\6\0\11\0\7\0\1\0\7\0\1\0\53\0"+
    "\1\0\16\0\6\0\163\0\10\0\1\0\2\0\2\0\12\0\6\0"+
    "\u2ba4\0\14\0\27\0\4\0\61\0\u2104\0\u016e\0\2\0\152\0\46\0"+
    "\7\0\14\0\5\0\5\0\1\0\1\0\12\0\1\0\15\0\1\0"+
    "\5\0\1\0\1\0\1\0\2\0\1\0\2\0\1\0\154\0\41\0"+
    "\u016b\0\22\0\100\0\2\0\66\0\50\0\15\0\3\0\20\0\20\0"+
    "\20\0\3\0\2\0\30\0\3\0\31\0\1\0\6\0\5\0\1\0"+
    "\207\0\2\0\1\0\4\0\1\0\13\0\12\0\7\0\32\0\4\0"+
    "\1\0\1\0\32\0\13\0\131\0\3\0\6\0\2\0\6\0\2\0"+
    "\6\0\2\0\3\0\3\0\2\0\3\0\2\0\22\0\3\0\4\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    32,    64,    96,    64,   128,   160,   192,   224,   256, 
      288,    64,   320,   352,   384,   416,    64,    64,    64,    64, 
      448,   480,   160,   512,   544,   576,   608,   640,   672,   704, 
      736,   768,   320,   800,   352,   832,   864,   896,   480,   928, 
      512,   960,   992,  1024,  1056,  1088,  1120,  1152,  1184,  1216, 
     1248,  1280,  1312,  1344,  1376,  1408,  1440,  1472,  1504,   160, 
       64,  1536,  1568,  1600,   160,  1632,    64
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\7\1\3\1\10\1\11"+
    "\1\12\1\3\1\13\1\14\1\15\1\16\1\3\1\7"+
    "\1\16\1\7\1\3\1\5\1\3\1\15\2\16\1\17"+
    "\1\20\1\17\1\21\1\22\1\23\1\24\40\3\42\0"+
    "\1\5\41\0\1\25\1\26\2\0\1\27\1\25\1\30"+
    "\3\0\1\27\1\0\3\27\1\31\3\0\2\27\3\25"+
    "\10\0\2\27\2\0\2\27\4\0\1\27\1\0\3\27"+
    "\1\31\3\0\5\27\10\0\1\32\4\0\1\32\17\0"+
    "\3\32\10\0\1\33\1\27\2\0\1\27\1\33\4\0"+
    "\1\27\1\0\3\27\1\31\3\0\2\27\3\33\10\0"+
    "\1\34\1\27\2\0\1\27\1\34\1\30\3\0\1\27"+
    "\1\0\3\27\1\31\3\0\2\27\3\34\17\0\1\35"+
    "\1\36\24\0\1\37\2\40\1\0\1\41\2\0\1\42"+
    "\6\0\1\41\2\0\1\41\1\0\1\40\14\0\1\37"+
    "\2\40\1\27\1\43\2\0\1\44\1\27\4\0\1\27"+
    "\1\41\2\27\1\43\1\31\1\40\2\0\5\27\10\0"+
    "\1\25\1\27\2\0\1\27\1\25\1\30\3\0\1\27"+
    "\1\0\3\27\1\31\3\0\2\27\3\25\10\0\1\25"+
    "\1\27\2\0\1\27\1\34\1\30\3\0\1\27\1\0"+
    "\3\27\1\31\3\0\2\27\2\34\1\25\10\0\1\45"+
    "\1\27\2\0\1\27\1\45\1\30\1\46\2\0\1\27"+
    "\1\0\3\27\1\31\3\0\2\27\3\45\10\0\1\47"+
    "\1\27\1\50\1\0\1\27\1\47\4\0\1\47\1\0"+
    "\3\27\1\31\3\0\1\47\1\27\3\47\10\0\1\51"+
    "\4\0\1\51\17\0\3\51\10\0\2\52\2\0\2\52"+
    "\4\0\1\52\1\0\3\52\4\0\5\52\10\0\1\32"+
    "\4\0\1\32\1\30\16\0\3\32\10\0\1\33\1\27"+
    "\2\0\1\27\1\33\1\30\3\0\1\27\1\0\3\27"+
    "\1\31\3\0\2\27\3\33\10\0\1\45\1\27\2\0"+
    "\1\27\1\45\1\30\3\0\1\27\1\0\3\27\1\31"+
    "\3\0\2\27\3\45\4\0\1\35\1\4\1\5\35\35"+
    "\14\36\1\53\23\36\2\0\1\40\12\0\2\54\2\0"+
    "\1\54\4\0\3\54\24\0\2\54\2\0\1\54\4\0"+
    "\3\54\24\0\2\41\2\0\1\41\4\0\3\41\13\0"+
    "\2\27\2\0\2\27\3\0\1\41\1\43\1\0\1\27"+
    "\1\43\1\27\1\31\2\0\1\41\2\43\3\27\10\0"+
    "\1\55\1\27\2\0\1\27\1\55\1\30\3\0\1\27"+
    "\1\0\3\27\1\31\3\0\2\27\3\55\10\0\1\56"+
    "\26\0\1\57\10\0\1\50\1\0\1\50\2\0\1\50"+
    "\4\0\1\50\10\0\1\50\1\0\3\50\10\0\2\52"+
    "\2\0\2\52\1\60\3\0\1\52\1\0\3\52\4\0"+
    "\5\52\4\0\13\36\1\5\1\53\23\36\1\0\1\37"+
    "\2\40\1\0\1\54\2\0\1\40\6\0\1\54\2\0"+
    "\1\54\1\0\1\40\17\0\1\61\1\62\1\63\1\0"+
    "\1\27\1\61\1\30\3\0\1\27\1\0\1\62\1\27"+
    "\1\62\1\31\1\64\2\63\2\62\3\61\10\0\1\65"+
    "\4\0\1\65\17\0\3\65\10\0\1\65\24\0\1\65"+
    "\1\0\1\65\10\0\2\66\2\0\1\52\1\66\4\0"+
    "\1\66\1\0\1\52\2\66\4\0\5\66\10\0\1\67"+
    "\1\27\2\0\1\27\1\67\1\30\3\0\1\27\1\0"+
    "\3\27\1\31\3\0\2\27\3\67\10\0\1\27\1\70"+
    "\1\71\1\0\2\27\4\0\1\27\1\0\1\70\1\27"+
    "\1\70\1\31\1\0\2\71\2\70\3\27\11\0\2\71"+
    "\11\0\1\71\1\0\1\71\2\0\4\71\14\0\2\63"+
    "\11\0\1\63\1\0\1\63\2\0\4\63\22\0\1\72"+
    "\30\0\2\66\2\0\1\52\1\66\1\60\3\0\1\66"+
    "\1\0\1\52\2\66\4\0\5\66\10\0\1\73\1\27"+
    "\2\0\1\27\1\73\1\30\3\0\1\27\1\0\3\27"+
    "\1\31\3\0\2\27\3\73\10\0\1\27\1\74\1\75"+
    "\1\0\2\27\4\0\1\27\1\0\1\74\1\27\1\74"+
    "\1\31\1\0\2\75\2\74\3\27\11\0\2\75\11\0"+
    "\1\75\1\0\1\75\2\0\4\75\13\0\1\76\4\0"+
    "\1\76\17\0\3\76\10\0\1\77\1\27\2\0\1\27"+
    "\1\77\1\30\3\0\1\27\1\0\3\27\1\31\3\0"+
    "\2\27\3\77\10\0\1\100\4\0\1\100\17\0\3\100"+
    "\10\0\1\33\1\27\2\0\1\27\1\33\1\30\3\0"+
    "\1\101\1\0\1\27\1\101\1\27\1\31\3\0\2\101"+
    "\3\33\10\0\1\102\4\0\1\102\17\0\3\102\10\0"+
    "\1\103\4\0\1\103\17\0\3\103\4\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  1,  1,  1,  1,  9,  1,  1,  1,  1, 
     9,  9,  9,  9,  1,  0,  0,  0,  0,  1,  1,  1,  0,  0,  0,  0, 
     0,  0,  0,  0,  1,  0,  1,  1,  1,  0,  0,  1,  1,  0,  0,  0, 
     1,  0,  0,  0,  0,  1,  1,  0,  0,  0,  1,  1,  9,  0,  1,  0, 
     1,  0,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[1664];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2280) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 66: 
          { return new Symbol(SimbolosTerminales.FECHA, 		yytext()); }
        case 68: break;
        case 53: 
          { return new Symbol(SimbolosTerminales.EMAIL, 		yytext()); }
        case 69: break;
        case 7: 
          {  return new Symbol(SimbolosTerminales.PLUS, 	yytext()); 	 }
        case 70: break;
        case 16: 
          {  return new Symbol(SimbolosTerminales.SEMI, 	yytext());	 }
        case 71: break;
        case 3: 
        case 4: 
          {                                }
        case 72: break;
        case 5: 
        case 9: 
        case 14: 
        case 15: 
        case 20: 
        case 25: 
        case 26: 
        case 27: 
        case 36: 
        case 40: 
        case 44: 
        case 48: 
        case 54: 
        case 58: 
        case 62: 
          {  return new Symbol(SimbolosTerminales.NUMBER, 		Double.parseDouble(yytext()));			 }
        case 73: break;
        case 59: 
        case 60: 
          { return new Symbol(SimbolosTerminales.MATRICULA, 	yytext()); }
        case 74: break;
        case 64: 
          { return new Symbol(SimbolosTerminales.DNI,			yytext()); }
        case 75: break;
        case 43: 
          { return new Symbol(SimbolosTerminales.NAME, 		yytext()); }
        case 76: break;
        case 19: 
          {  return new Symbol(SimbolosTerminales.EQUALS, 	yytext()); 	 }
        case 77: break;
        case 18: 
          {  return new Symbol(SimbolosTerminales.RPAREN, 	yytext());	 }
        case 78: break;
        case 17: 
          {  return new Symbol(SimbolosTerminales.LPAREN, 	yytext()); 	 }
        case 79: break;
        case 8: 
          {  return new Symbol(SimbolosTerminales.MINUS, 	yytext()); 	 }
        case 80: break;
        case 10: 
          {  return new Symbol(SimbolosTerminales.DIVIDED, yytext());	 }
        case 81: break;
        case 11: 
          {  return new Symbol(SimbolosTerminales.TIMES, 	yytext()); 	 }
        case 82: break;
        case 38: 
        case 39: 
          { return new Symbol(SimbolosTerminales.HEXADECIMAL, 	Long.decode(yytext()).doubleValue()); 	 }
        case 83: break;
        case 2: 
        case 6: 
        case 12: 
        case 13: 
          { System.err.println("warning: Unrecognized character '"+ yytext()+"' -- ignored" + " at : "+ (yyline+1) + " " + (yycolumn+1) + " " + yychar);  }
        case 84: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
              {     return new Symbol(EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
