/* The following code was generated by JFlex 1.3.5 on 19/5/21 15:47 */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 19/5/21 15:47 from the specification file
 * <tt>file:/C:/Users/claud/Desktop/Practica_final/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\37\1\3\1\2\1\0\1\3\1\1\16\37\4\0\1\3\1\53"+
    "\2\0\1\36\1\0\1\52\1\16\1\44\1\45\1\5\1\14\1\41"+
    "\1\15\1\12\1\4\1\6\11\7\1\46\1\40\1\50\1\47\1\51"+
    "\2\0\1\23\1\32\1\27\1\35\1\13\1\22\2\36\1\34\2\36"+
    "\1\24\1\33\1\31\1\30\2\36\1\20\1\25\1\17\1\21\1\26"+
    "\1\36\1\10\2\36\1\42\1\0\1\43\1\0\1\36\1\0\1\23"+
    "\1\32\1\27\1\35\1\13\1\22\2\36\1\34\2\36\1\24\1\33"+
    "\1\31\1\30\2\36\1\20\1\25\1\17\1\21\1\26\1\36\1\10"+
    "\2\36\1\0\1\11\2\0\41\37\2\0\4\36\4\0\1\36\2\0"+
    "\1\37\7\0\1\36\4\0\1\36\5\0\27\36\1\0\37\36\1\0"+
    "\u01ca\36\4\0\14\36\16\0\5\36\7\0\1\36\1\0\1\36\21\0"+
    "\160\37\5\36\1\0\2\36\2\0\4\36\1\0\1\36\6\0\1\36"+
    "\1\0\3\36\1\0\1\36\1\0\24\36\1\0\123\36\1\0\213\36"+
    "\1\0\5\37\2\0\246\36\1\0\46\36\2\0\1\36\6\0\51\36"+
    "\6\0\1\36\1\0\55\37\1\0\1\37\1\0\2\37\1\0\2\37"+
    "\1\0\1\37\10\0\33\36\4\0\4\36\15\0\6\37\5\0\1\36"+
    "\4\0\13\37\1\0\1\37\3\0\53\36\37\37\4\0\2\36\1\37"+
    "\143\36\1\0\1\36\10\37\1\0\6\37\2\36\2\37\1\0\4\37"+
    "\2\36\12\37\3\36\2\0\1\36\17\0\1\37\1\36\1\37\36\36"+
    "\33\37\2\0\131\36\13\37\1\36\16\0\12\37\41\36\11\37\2\36"+
    "\4\0\1\36\2\0\1\37\30\36\4\37\1\36\11\37\1\36\3\37"+
    "\1\36\5\37\22\0\31\36\3\37\4\0\13\36\65\0\25\36\1\0"+
    "\22\36\13\0\61\37\66\36\3\37\1\36\22\37\1\36\7\37\12\36"+
    "\2\37\2\0\12\37\1\0\20\36\3\37\1\0\10\36\2\0\2\36"+
    "\2\0\26\36\1\0\7\36\1\0\1\36\3\0\4\36\2\0\1\37"+
    "\1\36\7\37\2\0\2\37\2\0\3\37\1\36\10\0\1\37\4\0"+
    "\2\36\1\0\3\36\2\37\2\0\12\37\4\36\7\0\2\36\1\0"+
    "\1\37\2\0\3\37\1\0\6\36\4\0\2\36\2\0\26\36\1\0"+
    "\7\36\1\0\2\36\1\0\2\36\1\0\2\36\2\0\1\37\1\0"+
    "\5\37\4\0\2\37\2\0\3\37\3\0\1\37\7\0\4\36\1\0"+
    "\1\36\7\0\14\37\3\36\1\37\13\0\3\37\1\0\11\36\1\0"+
    "\3\36\1\0\26\36\1\0\7\36\1\0\2\36\1\0\5\36\2\0"+
    "\1\37\1\36\10\37\1\0\3\37\1\0\3\37\2\0\1\36\17\0"+
    "\2\36\2\37\2\0\12\37\1\0\1\36\7\0\1\36\6\37\1\0"+
    "\3\37\1\0\10\36\2\0\2\36\2\0\26\36\1\0\7\36\1\0"+
    "\2\36\1\0\5\36\2\0\1\37\1\36\7\37\2\0\2\37\2\0"+
    "\3\37\7\0\3\37\4\0\2\36\1\0\3\36\2\37\2\0\12\37"+
    "\1\0\1\36\20\0\1\37\1\36\1\0\6\36\3\0\3\36\1\0"+
    "\4\36\3\0\2\36\1\0\1\36\1\0\2\36\3\0\2\36\3\0"+
    "\3\36\3\0\14\36\4\0\5\37\3\0\3\37\1\0\4\37\2\0"+
    "\1\36\6\0\1\37\16\0\12\37\11\0\1\36\6\0\5\37\10\36"+
    "\1\0\3\36\1\0\27\36\1\0\20\36\3\0\1\36\7\37\1\0"+
    "\3\37\1\0\4\37\7\0\2\37\1\0\3\36\5\0\2\36\2\37"+
    "\2\0\12\37\20\0\1\36\3\37\1\0\10\36\1\0\3\36\1\0"+
    "\27\36\1\0\12\36\1\0\5\36\2\0\1\37\1\36\7\37\1\0"+
    "\3\37\1\0\4\37\7\0\2\37\7\0\1\36\1\0\2\36\2\37"+
    "\2\0\12\37\1\0\2\36\15\0\4\37\11\36\1\0\3\36\1\0"+
    "\51\36\2\37\1\36\7\37\1\0\3\37\1\0\4\37\1\36\5\0"+
    "\3\36\1\37\7\0\3\36\2\37\2\0\12\37\12\0\6\36\1\0"+
    "\3\37\1\0\22\36\3\0\30\36\1\0\11\36\1\0\1\36\2\0"+
    "\7\36\3\0\1\37\4\0\6\37\1\0\1\37\1\0\10\37\6\0"+
    "\12\37\2\0\2\37\15\0\60\36\1\37\2\36\7\37\4\0\10\36"+
    "\10\37\1\0\12\37\47\0\2\36\1\0\1\36\1\0\5\36\1\0"+
    "\30\36\1\0\1\36\1\0\12\36\1\37\2\36\11\37\1\36\2\0"+
    "\5\36\1\0\1\36\1\0\6\37\2\0\12\37\2\0\4\36\40\0"+
    "\1\36\27\0\2\37\6\0\12\37\13\0\1\37\1\0\1\37\1\0"+
    "\1\37\4\0\2\37\10\36\1\0\44\36\4\0\24\37\1\0\2\37"+
    "\5\36\13\37\1\0\44\37\11\0\1\37\71\0\53\36\24\37\1\36"+
    "\12\37\6\0\6\36\4\37\4\36\3\37\1\36\3\37\2\36\7\37"+
    "\3\36\4\37\15\36\14\37\1\36\17\37\2\0\46\36\1\0\1\36"+
    "\5\0\1\36\2\0\53\36\1\0\u014d\36\1\0\4\36\2\0\7\36"+
    "\1\0\1\36\1\0\4\36\2\0\51\36\1\0\4\36\2\0\41\36"+
    "\1\0\4\36\2\0\7\36\1\0\1\36\1\0\4\36\2\0\17\36"+
    "\1\0\71\36\1\0\4\36\2\0\103\36\2\0\3\37\40\0\20\36"+
    "\20\0\126\36\2\0\6\36\3\0\u026c\36\2\0\21\36\1\0\32\36"+
    "\5\0\113\36\3\0\13\36\7\0\15\36\1\0\4\36\3\37\13\0"+
    "\22\36\3\37\13\0\22\36\2\37\14\0\15\36\1\0\3\36\1\0"+
    "\2\37\14\0\64\36\40\37\3\0\1\36\3\0\2\36\1\37\2\0"+
    "\12\37\41\0\4\37\1\0\12\37\6\0\131\36\7\0\5\36\2\37"+
    "\42\36\1\37\1\36\5\0\106\36\12\0\37\36\1\0\14\37\4\0"+
    "\14\37\12\0\12\37\36\36\2\0\5\36\13\0\54\36\4\0\32\36"+
    "\6\0\12\37\46\0\27\36\5\37\4\0\65\36\12\37\1\0\35\37"+
    "\2\0\13\37\6\0\12\37\15\0\1\36\10\0\16\37\1\0\2\37"+
    "\77\0\5\37\57\36\21\37\7\36\4\0\12\37\21\0\11\37\14\0"+
    "\3\37\36\36\15\37\2\36\12\37\54\36\16\37\14\0\44\36\24\37"+
    "\10\0\12\37\3\0\3\36\12\37\44\36\2\0\11\36\7\0\53\36"+
    "\2\0\3\36\20\0\3\37\1\0\25\37\4\36\1\37\6\36\1\37"+
    "\2\36\3\37\1\36\5\0\300\36\72\37\1\0\5\37\u0116\36\2\0"+
    "\6\36\2\0\46\36\2\0\6\36\2\0\10\36\1\0\1\36\1\0"+
    "\1\36\1\0\1\36\1\0\37\36\2\0\65\36\1\0\7\36\1\0"+
    "\1\36\3\0\3\36\1\0\7\36\3\0\4\36\2\0\6\36\4\0"+
    "\15\36\5\0\3\36\1\0\7\36\16\0\5\37\32\0\5\37\20\0"+
    "\2\36\23\0\1\36\13\0\5\37\1\0\12\37\1\0\1\36\15\0"+
    "\1\36\20\0\15\36\3\0\40\36\20\0\15\37\4\0\1\37\3\0"+
    "\14\37\21\0\1\36\4\0\1\36\2\0\12\36\1\0\1\36\3\0"+
    "\5\36\6\0\1\36\1\0\1\36\1\0\1\36\1\0\4\36\1\0"+
    "\13\36\2\0\4\36\5\0\5\36\4\0\1\36\21\0\51\36\u0a77\0"+
    "\57\36\1\0\57\36\1\0\205\36\6\0\4\36\3\37\2\36\14\0"+
    "\46\36\1\0\1\36\5\0\1\36\2\0\70\36\7\0\1\36\17\0"+
    "\1\37\27\36\11\0\7\36\1\0\7\36\1\0\7\36\1\0\7\36"+
    "\1\0\7\36\1\0\7\36\1\0\7\36\1\0\7\36\1\0\40\37"+
    "\57\0\1\36\u01d5\0\3\36\31\0\11\36\6\37\1\0\5\36\2\0"+
    "\5\36\4\0\126\36\2\0\2\37\2\0\3\36\1\0\132\36\1\0"+
    "\4\36\5\0\53\36\1\0\136\36\21\0\40\36\60\0\20\36\u0200\0"+
    "\u19c0\36\100\0\u51fd\36\3\0\u048d\36\103\0\56\36\2\0\u010d\36\3\0"+
    "\20\36\12\37\2\36\24\0\57\36\1\37\4\0\12\37\1\0\37\36"+
    "\2\37\120\36\2\37\45\0\11\36\2\0\147\36\2\0\65\36\2\0"+
    "\11\36\52\0\15\36\1\37\3\36\1\37\4\36\1\37\27\36\5\37"+
    "\4\0\1\37\13\0\1\36\7\0\64\36\14\0\2\37\62\36\22\37"+
    "\12\0\12\37\6\0\22\37\6\36\3\0\1\36\1\0\2\36\13\37"+
    "\34\36\10\37\2\0\27\36\15\37\14\0\35\36\3\0\4\37\57\36"+
    "\16\37\16\0\1\36\12\37\6\0\5\36\1\37\12\36\12\37\5\36"+
    "\1\0\51\36\16\37\11\0\3\36\1\37\10\36\2\37\2\0\12\37"+
    "\6\0\27\36\3\0\1\36\3\37\62\36\1\37\1\36\3\37\2\36"+
    "\2\37\5\36\2\37\1\36\1\37\1\36\30\0\3\36\2\0\13\36"+
    "\5\37\2\0\3\36\2\37\12\0\6\36\2\0\6\36\2\0\6\36"+
    "\11\0\7\36\1\0\7\36\1\0\53\36\1\0\16\36\6\0\163\36"+
    "\10\37\1\0\2\37\2\0\12\37\6\0\u2ba4\36\14\0\27\36\4\0"+
    "\61\36\u2104\0\u016e\36\2\0\152\36\46\0\7\36\14\0\5\36\5\0"+
    "\1\36\1\37\12\36\1\0\15\36\1\0\5\36\1\0\1\36\1\0"+
    "\2\36\1\0\2\36\1\0\154\36\41\0\u016b\36\22\0\100\36\2\0"+
    "\66\36\50\0\15\36\3\0\20\37\20\0\20\37\3\0\2\36\30\0"+
    "\3\36\31\0\1\36\6\0\5\36\1\0\207\36\2\0\1\37\4\0"+
    "\1\36\13\0\12\37\7\0\32\36\4\0\1\36\1\0\32\36\13\0"+
    "\131\36\3\0\6\36\2\0\6\36\2\0\6\36\2\0\3\36\3\0"+
    "\2\36\3\0\2\36\22\0\3\37\4\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    44,    88,   132,    88,   176,    88,   220,   264,   308, 
       88,    88,   352,    88,    88,   396,   440,   484,   528,   572, 
      616,   660,   704,   748,   792,   836,   880,    88,    88,    88, 
       88,    88,    88,   924,   968,  1012,  1056,    88,    88,  1100, 
     1144,  1188,  1232,  1276,  1320,  1364,  1408,  1452,  1496,  1496, 
     1540,  1584,  1628,  1672,  1716,  1760,  1804,  1848,   308,  1892, 
     1936,  1980,    88,    88,    88,    88,  2024,  1232,  2068,  2112, 
     2112,  2156,    88,  2200,  2244,  2288,  2332,   308,  2376,  2420, 
     2464,   308,  2508,  2552,  2596,  2640,   308,   308,  2684,  2728, 
      308,  2772,  2816,  2860,  2904,  2948,  2992,   308,  3036,  3080, 
     3124,  3168,  3212,   308,  3256,  3300,   308,  3344,  3388,  3432, 
     3476,  3520,  3564,  3608,  3652,   308,  3696,   308,   308,  3740, 
     3784,   308
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\12\1\23\1\24\1\12\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\3\12\1\3\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\54\3\56\0\1\5\55\0\1\50\1\51\54\0"+
    "\2\52\1\53\1\0\1\54\47\0\2\55\2\0\1\56"+
    "\1\57\46\0\3\12\2\0\1\12\3\0\21\12\22\0"+
    "\3\12\2\0\1\12\3\0\12\12\1\60\6\12\14\0"+
    "\2\61\1\0\13\61\1\62\35\61\6\0\3\12\2\0"+
    "\1\12\3\0\1\12\1\63\17\12\22\0\3\12\2\0"+
    "\1\64\3\0\21\12\22\0\3\12\2\0\1\12\3\0"+
    "\4\12\1\65\10\12\1\66\3\12\22\0\3\12\2\0"+
    "\1\12\3\0\12\12\1\67\6\12\22\0\3\12\2\0"+
    "\1\12\3\0\15\12\1\70\3\12\22\0\3\12\2\0"+
    "\1\71\3\0\21\12\22\0\3\12\2\0\1\12\3\0"+
    "\4\12\1\72\14\12\22\0\3\12\2\0\1\12\3\0"+
    "\1\12\1\73\17\12\22\0\3\12\2\0\1\12\3\0"+
    "\11\12\1\74\7\12\22\0\3\12\2\0\1\12\3\0"+
    "\11\12\1\75\7\12\22\0\3\12\2\0\1\12\3\0"+
    "\15\12\1\76\3\12\63\0\1\77\53\0\1\100\53\0"+
    "\1\101\53\0\1\102\4\0\1\50\1\4\1\5\51\50"+
    "\5\51\1\103\46\51\6\0\2\52\2\0\1\54\47\0"+
    "\2\104\1\0\1\104\1\0\1\104\6\0\2\104\3\0"+
    "\1\104\2\0\1\104\2\0\1\104\24\0\2\54\52\0"+
    "\2\55\2\0\1\54\47\0\2\105\52\0\2\106\4\0"+
    "\2\107\44\0\3\12\2\0\1\12\3\0\1\110\20\12"+
    "\32\0\1\111\43\0\3\12\2\0\1\12\3\0\2\12"+
    "\1\112\16\12\22\0\3\12\2\0\1\12\3\0\4\12"+
    "\1\113\14\12\22\0\3\12\2\0\1\12\3\0\5\12"+
    "\1\114\13\12\22\0\3\12\2\0\1\12\3\0\12\12"+
    "\1\115\6\12\22\0\3\12\2\0\1\12\3\0\16\12"+
    "\1\116\2\12\22\0\3\12\2\0\1\12\3\0\12\12"+
    "\1\117\6\12\22\0\3\12\2\0\1\12\3\0\10\12"+
    "\1\120\10\12\22\0\3\12\2\0\1\12\3\0\1\12"+
    "\1\121\17\12\22\0\3\12\2\0\1\12\3\0\1\122"+
    "\20\12\22\0\3\12\2\0\1\12\3\0\11\12\1\123"+
    "\7\12\22\0\3\12\2\0\1\124\3\0\21\12\14\0"+
    "\4\51\1\5\1\103\46\51\6\0\2\105\3\0\1\57"+
    "\46\0\2\106\52\0\3\12\2\0\1\125\3\0\11\12"+
    "\1\126\7\12\22\0\3\12\2\0\1\127\3\0\21\12"+
    "\22\0\3\12\2\0\1\12\3\0\5\12\1\130\13\12"+
    "\22\0\3\12\2\0\1\12\3\0\6\12\1\112\12\12"+
    "\22\0\3\12\2\0\1\12\3\0\6\12\1\131\5\12"+
    "\1\132\4\12\22\0\3\12\2\0\1\12\3\0\11\12"+
    "\1\133\7\12\22\0\3\12\2\0\1\12\3\0\1\134"+
    "\20\12\22\0\3\12\2\0\1\12\3\0\4\12\1\135"+
    "\14\12\22\0\3\12\2\0\1\12\3\0\5\12\1\136"+
    "\13\12\22\0\3\12\2\0\1\12\3\0\12\12\1\137"+
    "\6\12\22\0\3\12\2\0\1\12\3\0\1\12\1\140"+
    "\17\12\22\0\3\12\2\0\1\12\3\0\12\12\1\141"+
    "\6\12\22\0\3\12\2\0\1\12\3\0\15\12\1\142"+
    "\3\12\22\0\3\12\2\0\1\12\3\0\15\12\1\143"+
    "\3\12\22\0\3\12\2\0\1\12\3\0\11\12\1\144"+
    "\7\12\22\0\3\12\2\0\1\12\3\0\10\12\1\145"+
    "\10\12\22\0\3\12\2\0\1\146\3\0\21\12\22\0"+
    "\3\12\2\0\1\12\3\0\1\147\20\12\22\0\3\12"+
    "\2\0\1\12\3\0\11\12\1\150\7\12\22\0\3\12"+
    "\2\0\1\12\3\0\10\12\1\151\10\12\22\0\3\12"+
    "\2\0\1\152\3\0\21\12\22\0\3\12\2\0\1\12"+
    "\3\0\1\12\1\153\17\12\22\0\3\12\2\0\1\12"+
    "\3\0\1\154\20\12\22\0\3\12\2\0\1\12\3\0"+
    "\4\12\1\155\14\12\22\0\3\12\2\0\1\12\3\0"+
    "\1\12\1\156\17\12\22\0\3\12\2\0\1\157\3\0"+
    "\21\12\22\0\3\12\2\0\1\12\3\0\12\12\1\160"+
    "\6\12\22\0\3\12\2\0\1\161\3\0\21\12\22\0"+
    "\3\12\2\0\1\12\3\0\12\12\1\162\6\12\22\0"+
    "\3\12\2\0\1\12\3\0\4\12\1\163\14\12\22\0"+
    "\3\12\2\0\1\12\3\0\6\12\1\164\12\12\22\0"+
    "\3\12\2\0\1\12\3\0\1\165\20\12\22\0\3\12"+
    "\2\0\1\12\3\0\1\12\1\166\17\12\22\0\3\12"+
    "\2\0\1\12\3\0\11\12\1\166\7\12\22\0\3\12"+
    "\2\0\1\12\3\0\6\12\1\167\12\12\22\0\3\12"+
    "\2\0\1\12\3\0\1\12\1\170\17\12\22\0\3\12"+
    "\2\0\1\12\3\0\4\12\1\171\14\12\22\0\3\12"+
    "\2\0\1\12\3\0\6\12\1\172\12\12\14\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  9,  1,  1,  1,  9,  9,  1,  9,  9,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9,  9,  9,  9, 
     9,  1,  1,  1,  1,  9,  9,  0,  0,  0,  0,  1,  1,  1,  0,  1, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9, 
     9,  9,  0,  1,  1,  1,  0,  1,  9,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3828];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2312) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 103: 
          {  return symbolFactory.newSymbol("VARTYPE",    	VARTYPE, 		yytext()); 											 }
        case 123: break;
        case 27: 
          {  return symbolFactory.newSymbol("SEMI", 		SEMI); 															 }
        case 124: break;
        case 14: 
          {  return symbolFactory.newSymbol("MINUS", 		MINUS); 														 }
        case 125: break;
        case 13: 
          {  return symbolFactory.newSymbol("PLUS", 		PLUS); 															 }
        case 126: break;
        case 6: 
          {  return symbolFactory.newSymbol("TIMES", 		TIMES); 														 }
        case 127: break;
        case 37: 
          {  return symbolFactory.newSymbol("AND", 	    AND);															 }
        case 128: break;
        case 38: 
          {  return symbolFactory.newSymbol("NOT", 	    NOT);															 }
        case 129: break;
        case 81: 
          {  return symbolFactory.newSymbol("NOT", 	    NOT); 															 }
        case 130: break;
        case 3: 
        case 4: 
          {                               																					 }
        case 131: break;
        case 2: 
        case 15: 
        case 33: 
        case 34: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 132: break;
        case 36: 
          {  return symbolFactory.newSymbol("MAYORQUE", 	MAYORQUE); 														 }
        case 133: break;
        case 118: 
          {  return symbolFactory.newSymbol("WHILE", 	  	WHILE); 														 }
        case 134: break;
        case 5: 
          {  return symbolFactory.newSymbol("DIVISION", 	DIVISION); 														 }
        case 135: break;
        case 24: 
          {  return symbolFactory.newSymbol("UMINUS", 		UMINUS); 														 }
        case 136: break;
        case 11: 
          {  return symbolFactory.newSymbol("PUNTO", 	    PUNTO); 														 }
        case 137: break;
        case 63: 
          {  return symbolFactory.newSymbol("IGUALQUE", 	IGUALQUE); 														 }
        case 138: break;
        case 115: 
          {  return symbolFactory.newSymbol("THEN", 	    THEN); 															 }
        case 139: break;
        case 90: 
          {  return symbolFactory.newSymbol("ELSE", 	    ELSE); 														     }
        case 140: break;
        case 32: 
          {  return symbolFactory.newSymbol("RPAREN", 		RPAREN); 														 }
        case 141: break;
        case 49: 
        case 72: 
          {  return symbolFactory.newSymbol("CARACTER", 	CARACTER, 		yytext()); 					         }
        case 142: break;
        case 58: 
          {  return symbolFactory.newSymbol("OR", 	      	OR); 														     }
        case 143: break;
        case 67: 
          {  return symbolFactory.newSymbol("ENTERO",   	ENTERO, 	  	Long.decode(yytext()).doubleValue());				 }
        case 144: break;
        case 117: 
          {  return symbolFactory.newSymbol("VARTYPE", 	VARTYPE, 		yytext());											 }
        case 145: break;
        case 87: 
          {  return symbolFactory.newSymbol("VARTYPE",		VARTYPE, 		yytext());											 }
        case 146: break;
        case 10: 
          {  return symbolFactory.newSymbol("OR", 	        OR);															 }
        case 147: break;
        case 65: 
          {  return symbolFactory.newSymbol("MAYORIGQUE",  MAYORIGQUE); 													 }
        case 148: break;
        case 7: 
        case 8: 
        case 44: 
          {  return symbolFactory.newSymbol("ENTERO",   	ENTERO, 	  	Double.parseDouble(yytext()));					 }
        case 149: break;
        case 35: 
          {  return symbolFactory.newSymbol("MENORQUE", 	MENORQUE); 														 }
        case 150: break;
        case 77: 
          {  return symbolFactory.newSymbol("AND", 	    AND); 														     }
        case 151: break;
        case 31: 
          {  return symbolFactory.newSymbol("LPAREN", 		LPAREN); 														 }
        case 152: break;
        case 9: 
        case 12: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 22: 
        case 23: 
        case 25: 
        case 26: 
        case 47: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 56: 
        case 57: 
        case 59: 
        case 60: 
        case 61: 
        case 71: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 78: 
        case 79: 
        case 80: 
        case 82: 
        case 83: 
        case 84: 
        case 85: 
        case 88: 
        case 89: 
        case 91: 
        case 92: 
        case 93: 
        case 94: 
        case 95: 
        case 96: 
        case 98: 
        case 99: 
        case 100: 
        case 101: 
        case 102: 
        case 104: 
        case 105: 
        case 107: 
        case 108: 
        case 109: 
        case 110: 
        case 111: 
        case 112: 
        case 113: 
        case 114: 
        case 116: 
        case 119: 
        case 120: 
          {  return symbolFactory.newSymbol("IDENT",     	IDENT, 	    		yytext()); 					                 }
        case 153: break;
        case 64: 
          {  return symbolFactory.newSymbol("MENORIGQUE", 	MENORIGQUE); 												     }
        case 154: break;
        case 62: 
          {  return symbolFactory.newSymbol("ASIGNACION", 	ASIGNACION);													 }
        case 155: break;
        case 55: 
          {  return symbolFactory.newSymbol("IF", 	      	IF); 														     }
        case 156: break;
        case 106: 
          {  return symbolFactory.newSymbol("VECTOR", 	  	VECTOR); 														 }
        case 157: break;
        case 97: 
          {  return symbolFactory.newSymbol("ENDIF", 	  	ENDIF); 														 }
        case 158: break;
        case 43: 
        case 45: 
        case 68: 
          {  return symbolFactory.newSymbol("REAL", 	    REAL, 	    	Double.parseDouble(yytext())); 					 }
        case 159: break;
        case 69: 
          {  return symbolFactory.newSymbol("REAL",  		REAL, 			Double.parseDouble(yytext())); 					 }
        case 160: break;
        case 86: 
          {  return symbolFactory.newSymbol("BOOLEAN",   	BOOLEAN, 	  	yytext()); 				 }
        case 161: break;
        case 121: 
          {  return symbolFactory.newSymbol("ENDWHILE",  	ENDWHILE); 														 }
        case 162: break;
        case 30: 
          {  return symbolFactory.newSymbol("RBRACKET",  	RBRACKET); 													     }
        case 163: break;
        case 29: 
          {  return symbolFactory.newSymbol("LBRACKET",  	LBRACKET); 													     }
        case 164: break;
        case 28: 
          {  return symbolFactory.newSymbol("COMA", 	  	COMA); 															 }
        case 165: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
