
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 17;
  public static final int UMINUS = 20;
  public static final int ENTERO = 32;
  public static final int LPAREN = 15;
  public static final int SEMI = 14;
  public static final int MINUS = 22;
  public static final int RPAREN = 16;
  public static final int NOT = 11;
  public static final int AND = 9;
  public static final int MENORIGQUE = 27;
  public static final int IGUALQUE = 29;
  public static final int MAYORQUE = 26;
  public static final int CARACTER = 35;
  public static final int OR = 10;
  public static final int PLUS = 21;
  public static final int IF = 6;
  public static final int ENDWHILE = 4;
  public static final int EOF = 0;
  public static final int BOOLEAN = 34;
  public static final int MAYORIGQUE = 28;
  public static final int RBRACKET = 18;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int IDENT = 30;
  public static final int VECTOR = 2;
  public static final int ASIGNACION = 19;
  public static final int REAL = 33;
  public static final int VARTYPE = 31;
  public static final int MENORQUE = 25;
  public static final int TIMES = 23;
  public static final int ENDIF = 5;
  public static final int ELSE = 7;
  public static final int PUNTO = 12;
  public static final int WHILE = 3;
  public static final int THEN = 8;
  public static final int DIVISION = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VECTOR",
  "WHILE",
  "ENDWHILE",
  "ENDIF",
  "IF",
  "ELSE",
  "THEN",
  "AND",
  "OR",
  "NOT",
  "PUNTO",
  "COMA",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "ASIGNACION",
  "UMINUS",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVISION",
  "MENORQUE",
  "MAYORQUE",
  "MENORIGQUE",
  "MAYORIGQUE",
  "IGUALQUE",
  "IDENT",
  "VARTYPE",
  "ENTERO",
  "REAL",
  "BOOLEAN",
  "CARACTER"
  };
}

