
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int LN = 8;
  public static final int NUMBER = 13;
  public static final int MEM = 12;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int DIVIDED = 6;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int TIMES = 5;
  public static final int EQUALS = 11;
  public static final int LPAREN = 9;
  public static final int EXP = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDED",
  "EXP",
  "LN",
  "LPAREN",
  "RPAREN",
  "EQUALS",
  "MEM",
  "NUMBER"
  };
}

