
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int AND = 14;
  public static final int IDENT = 20;
  public static final int PLUS = 3;
  public static final int OR = 15;
  public static final int RPAREN = 9;
  public static final int SEMI = 2;
  public static final int DIVISION = 5;
  public static final int NOT = 16;
  public static final int MAYORQUE = 11;
  public static final int LPAREN = 8;
  public static final int IGUALQUE = 12;
  public static final int COMA = 18;
  public static final int ASIGNACION = 13;
  public static final int EOF = 0;
  public static final int VECTOR = 17;
  public static final int MENORQUE = 10;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int VARTYPE = 21;
  public static final int ENTERO = 19;
  public static final int UMINUS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "DIVISION",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "MENORQUE",
  "MAYORQUE",
  "IGUALQUE",
  "ASIGNACION",
  "AND",
  "OR",
  "NOT",
  "VECTOR",
  "COMA",
  "ENTERO",
  "IDENT",
  "VARTYPE"
  };
}

